# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  lane :build_free_debug do
    gradle(task: "clean")
#     gradle(task: "test")
    gradle(task: "assembleFreeDebug")
    firebase_app_distribution(
        app: "1:66413692087:android:26b41a8322dbc3b0b8b932",
        firebase_cli_token: "1//0gB9tGShH62csCgYIARAAGBASNwF-L9IrNTbnIXV58S8h-B3C0X1_rEAS8lVbmbU5zVPqGvBhueZ2d8Rbzbg-IBaUNtwKQMyzsk8",
        debug: true,
        android_artifact_type: "APK",
        testers: "beranjugaming@gmail.com",
        android_artifact_path: ENV['GRADLE_APK_OUTPUT_PATH'],
        release_notes: "Movie ku free version"
    )
  end
end
